server:
  port: 8001
spring:
  datasource:
    url: jdbc:mysql://49.235.235.143:3306/eladmin??serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: Root123@
    driver-class-name: com.mysql.jdbc.Driver
#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
